### ISSUE TITLE
Display issue with chrome

### ISSUE THREAD

**Issue by aragua** [free-electrons/elixir#12]
My web browser (chrome 57.0.2987.98) fail to display lxr.free-electrons.com correctly.
My system is a Debian 9 and I get the version from apt:
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

Everything works fine with firefox on the same machine

![lxrissue](https://cloud.githubusercontent.com/assets/646901/26504079/6da227b4-4243-11e7-87e4-94ee8cdab557.png)

.

**Comment by michaelopdenacker** [comment]
It's a browser cache issue. 
(use ctrl+alt+r in chrome on Linux)

Here's a list of instructions for various browsers:
https://www.getfilecloud.com/blog/2015/03/tech-tip-how-to-do-hard-refresh-in-browsers/#.WShYk3Z95hE

Here's a branch addressing that:
https://github.com/zo/elixir/tree/hotfix/cache-invalidation
to tell the browsers that the style has changed.
