### ISSUE TITLE
README Out of Date

### ISSUE THREAD

**Issue by modelrockettier** [free-electrons/elixir#14]
Hi, I've been working on setting up my own copy of Elixir with the Linux kernel and discovered that the README.md file is out of date and no longer reflects how Elixir is set up and configured.

1. Elixir also depends on the jinja2 and pygments python libraries which are not mentioned in the README.

2. The example Apache configuration uses the LXR_DATA_DIR and LXR_REPO_DIR for configuration (just like update.py), however web.py overrides those environment variables based on what's in the undocumented LXR_PROJ_DIR environment variable.  This also has the side effect that web.py requires the data and repo directories to be in a specific (and undocumented) structure.

    So consequently, the example directory structure of LXR_DATA_DIR=/srv/elixir-data, LXR_REPO_DIR=/srv/git/linux will not work (as it differs from web.py's assumed directory structure).

3. The URL scheme in the example Apache configuration also differs from what web.py uses.  For example, to access v4.10 of the linux kernel source code, the example configuration uses ^/source, ^/ident, etc. whereas web.py uses ^/linux/v4.10/source, ^/linux/v4.10/ident, etc.

**Comment by pokazef** [comment]
Hi,

Yes, I have left the documentation to lag behind the code for quite a while, sorry :(

Thank you for the report, I'll update it right away.
