### ISSUE TITLE
Tabs in kernel source is showing as 4 spaces, not 8

### ISSUE THREAD

**Issue by gregkh** [free-electrons/elixir#15]
As we all know, the correct indentation for tabs in kernel sources is 8, not 4.

One bad side affect is that some previously correctly lined up comments and code are now incorrect when viewing online.

Oh and if anyone ever cuts/pastes from the web view, it will be totally incorrect in their editor :)

**Comment by tpetazzoni** [comment]
Hehe, thanks @gregkh for this bug report. I also noticed this the other day. However, copy/paste works fine: try it out, it properly copies tabs, and therefore if you paste into a text editor configured for tab = 8 spaces, the code is correct.

However, I agree that it would be definitely be good to fix this from a layout point of view.

**Comment by atenart** [comment]
Fixed by ad66abe88c773c912cf04cefb8ea9dcf77ebb38e.
Thanks!

**Comment by gregkh** [comment]
Ah, didn't notice that cut/paste worked, it seemed like it was 4 spaces here, sorry.

And thanks for the quick response!

And also for the updated tool, very nice work.

**Comment by pokazef** [comment]
I just pulled the fix into the production tree.
