### ISSUE TITLE
Stacktrace when running elixir on php's source code

### ISSUE THREAD

**Issue by jvoisin** [free-electrons/elixir#19]
Hello,
I have a reproductible stacktrace when running elixir on [php-src](https://github.com/php/php-src)
```python
D: 15100
Traceback (most recent call last):
  File "./update.py", line 141, in <module>
    updateDefinitions (newBlobs)
  File "./update.py", line 84, in updateDefinitions
    line = int (line.decode())
ValueError: invalid literal for int() with base 10: 'function'
````

**Comment by pokazef** [comment]
This is due to the way ctags handles C++ operator overloading. I'm testing a fix right now.

**Comment by jvoisin** [comment]
PHP is written in C code, not C++.

**Comment by pokazef** [comment]
> PHP is written in C code, not C++.

It seems parts of the PCRE library [were](https://github.com/php/php-src/blob/e623e5352d8c42619a03d76fd999031ad927576d/ext/pcre/pcrelib/pcre_stringpiece.h#L107), at some point.

**Comment by jvoisin** [comment]
PHP is full of surprises

**Comment by pokazef** [comment]
Fun fact: I originally wrote Elixir in PHP and then translated it to Python.

**Comment by jvoisin** [comment]
![]( https://media.giphy.com/media/pVAMI8QYM42n6/giphy.gif )
