### ISSUE TITLE
Remove spaces before identifier's name before searching the database

### ISSUE THREAD

**Issue by bhumikagoyal** [free-electrons/elixir#22]
I am frequent user of elixir and one issue that I encountered is while searching for an identifier if I put a space before the identifier's name in Search Identifier box, it does not show any results.
If I search the same identifier without a space before the name, I get results. 
So, while searching for the identifier in the db, spaces before the identifier should be removed first.

I can create a PR proposing this fix.

Searching without space: string == "fpga_bridge_ops"
![selection_056](https://user-images.githubusercontent.com/6457715/27685619-aff835ea-5cec-11e7-98d5-5bdc9c762e95.png)

Searching with space: string == "   fpga_bridge_ops"
![selection_057](https://user-images.githubusercontent.com/6457715/27685629-b5e3d298-5cec-11e7-96db-4d20fd8c8f64.png)

**Comment by pokazef** [comment]
Thanks for the feedback, it should now be working.

**Comment by bhumikagoyal** [comment]
Yeah, thanks :)
