### ISSUE TITLE
IndexError with python

### ISSUE THREAD

**Issue by tookilt** [free-electrons/elixir#26]
hi,
`$ ./query.py`  command is very good, but when I use the chrome browser, It error
![_20170706092514](https://user-images.githubusercontent.com/21964210/27891762-3febbb54-622e-11e7-8241-815cfe11f580.png)

**Comment by pokazef** [comment]
Hi, could you try running `./script.sh list-tags -h` manually and see if you get a short line somewhere?

**Comment by tookilt** [comment]
It print `XXX XXX tag_3.10.0-514`, can I use it?

**Comment by pokazef** [comment]
Yes, `p.split(b' ')[2]` should yield `tag_3.10.0-514`... I don't understand what's wrong here.

Is your git repo public? If so, maybe I can try to reproduce your bug on my own.
