### ISSUE TITLE
Parser problem screws up cross reference

### ISSUE THREAD

**Issue by hugelgupf** [free-electrons/elixir#29]
Anything after this line is not parsed and hence not in the cross-reference:

http://elixir.free-electrons.com/linux/v3.11.10/source/fs/namespace.c#L974

E.g. a search for the identifier vfs_kern_mount shows references to line 775 and 805 in namespace.c, but actually it's called on line 1998 and 2691 and 2761 and you get the idea.

**Comment by pokazef** [comment]
Thanks for the report. I've corrected the parsing bug but the database will need to be regenerated, so expect a full fix by tomorrow.

**Comment by hugelgupf** [comment]
Thanks!
