### ISSUE TITLE
Checking line numbers from content management system displays

### ISSUE THREAD

**Issue by elfring** [free-electrons/elixir#32]
I came along a source file where I would like to refer to the beginning of the function “write_regs” (for [a corresponding software development discussion](https://patchwork.kernel.org/patch/9956771/ "Update suggestion for go7007: Use common error handling code in s2250_probe()")).
It seems that the following links would be appropriate in principle at the moment.
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/media/usb/go7007/s2250-board.c?h=v4.14-rc1#n302
* http://elixir.free-electrons.com/linux/v4.14-rc1/source/drivers/media/usb/go7007/s2250-board.c#L298

Now I wonder about the shown line numbers. How could they be different when they should refer to the same source code place according to the used version tag?

**Comment by alexandrebelloni** [comment]
Both files are the same and are numbered the same way. Your git.kernel.org link is pointing to the for() line in the write_regs function while the elixir link points to the beginning of the write_regs functions.

**Comment by elfring** [comment]
How are the chances to use consistent line numbers from displays in involved content management systems?
(Can the font size selection matter?)

**Comment by alexandrebelloni** [comment]
I suspect this has been silently fixed in the meantime

**Comment by elfring** [comment]
Should any more HTML displays be improved in the way that the line number column fits really to the corresponding source code line?
