### ISSUE TITLE
web.py could not work.

### ISSUE THREAD

**Issue by marryton007** [free-electrons/elixir#39]
It gets error while acceess the  [eos](https://github.com/EOSIO/eos) project with follow url
http://192.168.50.159/lxr-eos/latest/source

But access the zephyr project is good.
http://192.168.50.159/zephyr/latest/source

The web page report:

```
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
```

I got the follow error from apache error_log:

```
[Fri Jun 29 20:47:49.231913 2018] [http:error] [pid 775] [client 192.168.50.97:51215] AH02429: Response header name '<!--' contains invalid characters, aborting request
```

My environment:
OS: centos7
web server: apache 2.4.6
my apahce config file:
[root@localhost httpd]# cat sites-available/lxr.eos.conf

```
<VirtualHost *:80>
    ServerName lxr.eos.com
    DocumentRoot "/data/app/workspace/git/elixir/http"

    RewriteEngine on
    RewriteRule "^/$" "/lxr-eos/latest/source" [R]
    RewriteRule "^/.*/(source|ident|search)" "/web.py" [PT]
    <Directory "/data/app/workspace/git/elixir/http">
        Options Indexes FollowSymLinks ExecCGI
        AllowOverride All
        AddHandler cgi-script .cgi .py
        Require all granted
        SetEnv PYTHONIOENCODING utf-8
        SetEnv LXR_PROJ_DIR /data/home/jiaxi/workspace/job
    </Directory>
</VirtualHost>
```
project directory(contains zephyr and [eos](https://github.com/EOSIO/eos)): 
[root@localhost httpd]# ls ~jiaxi/workspace/job/zephyr/
data  repo

[jiaxi@localhost elixir]$ ls ~/workspace/job/lxreos/
data  repo

any suggestion is good, thanks.

**Comment by marryton007** [comment]
It works now,  I forgot install The Jinja2 and Pygments Python libraries.  Error or debug messages for helpful but I can't found.

**Comment by michaelopdenacker** [comment]
Hi,
Thank you for documenting this issue!
Cheers,
Michael.
