### ISSUE TITLE
Identifier search doesn't find all function occurrences

### ISSUE THREAD

**Issue by lategoodbye** [free-electrons/elixir#5]
If i try to search the function msleep via identifier search, i get in Elixir only 4 hits instead of 1627 hits in the old version.

**Comment by pokazef** [comment]
For the moment, idententifiers are filtered with ad-hoc syntactic rules to prevent many keywords from being wrongly identified (see isIdent() in lib.py).

I'll loosen the rules and regenerate a database shortly.

**Comment by pokazef** [comment]
After commit e4a84c81e37b6e50a822f859a81440b8f71e3bd7, "msleep" and "jiffies" are matched but other lowercase-only identifiers shorter than 6 chars aren't, yet.

**Comment by lategoodbye** [comment]
Thanks
