### ISSUE TITLE
Missing http://elixir.free-electrons.com/ident for bookmarks

### ISSUE THREAD

**Issue by petersenna** [free-electrons/elixir#8]
LXR has a convenient http://lxr.free-electrons.com/ident that is friendly for bookmarking. Every new stable release updates this URL. However elixir doesn't have that and I did not find anyway of having a bookmark to identifier search that won't require me to edit bookmarks on every release.

**Comment by michaelopdenacker** [comment]
Hi Peter,

Nice to hear from you. Thank you for your review of Elixir!
Indeed, we need to find a way to make version independent references that always refer to the latest available release. In particular, we need that for our kernel training materials. :)

I let Mikael Bouillot comment on what's possible.

Thanks again,

Michael.

**Comment by michaelopdenacker** [comment]
Closed this issue by mistake (just pressed the wrong button). Of course, it's still open.

**Comment by pokazef** [comment]
Hi Peter,

The new URL scheme for Elixir was designed so that all content is permanent, but that makes browsing the latest (or default) version difficult.

I'm going to define a virtual version that follows the latest release so that you can browse and bookmark pages from it.

**Comment by pokazef** [comment]
I implemented a 'latest' virtual version. For example: http://elixir.free-electrons.com/linux/latest/ident/GFP_KERNEL

**Comment by petersenna** [comment]
This is pretty cool. Thanks a lot!
